// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fbognini.EfCoreLocalization.Persistence;

#nullable disable

namespace SampleWebApp.Migrations
{
    [DbContext(typeof(EfCoreLocalizationDbContext))]
    [Migration("20260104083206_Localization")]
    partial class Localization
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("localization")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("fbognini.EfCoreLocalization.Persistence.Entities.Language", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)")
                        .IsFixedLength();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Languages", "localization");
                });

            modelBuilder.Entity("fbognini.EfCoreLocalization.Persistence.Entities.Text", b =>
                {
                    b.Property<string>("TextId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("TextId", "ResourceId");

                    b.ToTable("Texts", "localization");
                });

            modelBuilder.Entity("fbognini.EfCoreLocalization.Persistence.Entities.Translation", b =>
                {
                    b.Property<string>("LanguageId")
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)")
                        .IsFixedLength();

                    b.Property<string>("TextId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("LanguageId", "TextId", "ResourceId");

                    b.HasIndex("TextId", "ResourceId");

                    b.ToTable("Translations", "localization");
                });

            modelBuilder.Entity("fbognini.EfCoreLocalization.Persistence.Entities.Translation", b =>
                {
                    b.HasOne("fbognini.EfCoreLocalization.Persistence.Entities.Language", "Language")
                        .WithMany("Translations")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fbognini.EfCoreLocalization.Persistence.Entities.Text", "Text")
                        .WithMany("Translations")
                        .HasForeignKey("TextId", "ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Text");
                });

            modelBuilder.Entity("fbognini.EfCoreLocalization.Persistence.Entities.Language", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("fbognini.EfCoreLocalization.Persistence.Entities.Text", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
